//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectDependencyGraph.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubjectDependencyGraph.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;NBNEMI&quot;,
        ///    &quot;name&quot;: &quot;Mérnökinformatikus&quot;,
        ///    &quot;length&quot;: &quot;7&quot;,
        ///    &quot;mustChoseCredit&quot;: &quot;18&quot;,
        ///    &quot;chosableCredit&quot;: &quot;10&quot;,
        ///    &quot;startingSpecSemester&quot;: &quot;4&quot;,
        ///    &quot;specialisations&quot;: [
        ///      {
        ///        &quot;id&quot;: &quot;NBNEMI-AI-BD&quot;,
        ///        &quot;name&quot;: &quot;Big Data és üzleti intelligencia specializáció&quot;,
        ///        &quot;length&quot;: &quot;4&quot;,
        ///        &quot;mustChoseCredit&quot;: null,
        ///        &quot;chosableCredit&quot;: null,
        ///        &quot;startingSpecSemester&quot;: null,
        ///        &quot;parent&quot;: &quot;NBNEMI&quot;,
        ///        &quot;subjects&quot;: [
        ///          {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OENIK_E {
            get {
                return ResourceManager.GetString("OENIK-E", resourceCulture);
            }
        }
    }
}
