//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectDependencyGraph.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubjectDependencyGraph.Blazor.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllabi.
        /// </summary>
        public static string Syllabi {
            get {
                return ResourceManager.GetString("Syllabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosable credit.
        /// </summary>
        public static string Syllabus_ChosableCredit {
            get {
                return ResourceManager.GetString("Syllabus.ChosableCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Syllabus_Id {
            get {
                return ResourceManager.GetString("Syllabus.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Syllabus_Length {
            get {
                return ResourceManager.GetString("Syllabus.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory choosable credit.
        /// </summary>
        public static string Syllabus_MustChoseCredit {
            get {
                return ResourceManager.GetString("Syllabus.MustChoseCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Syllabus_Name {
            get {
                return ResourceManager.GetString("Syllabus.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisations.
        /// </summary>
        public static string Syllabus_Specialisations {
            get {
                return ResourceManager.GetString("Syllabus.Specialisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation starting semester.
        /// </summary>
        public static string Syllabus_StartingSpecSemester {
            get {
                return ResourceManager.GetString("Syllabus.StartingSpecSemester", resourceCulture);
            }
        }
    }
}
