//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectDependencyGraph.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubjectDependencyGraph.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;NBNEMI&quot;,
        ///    &quot;name&quot;: &quot;Mérnökinformatikus&quot;,
        ///    &quot;length&quot;: 7,
        ///    &quot;requiredMustChoseCredit&quot;: 18,
        ///    &quot;requiredChosableCredit&quot;: 10,
        ///    &quot;startingSpecSemester&quot;: 4,
        ///    &quot;specialisations&quot;: [
        ///      {
        ///        &quot;id&quot;: &quot;NBNEMI-AI-BD&quot;,
        ///        &quot;name&quot;: &quot;Big Data és üzleti intelligencia specializáció&quot;,
        ///        &quot;length&quot;: 4,
        ///        &quot;parent&quot;: &quot;NBNEMI&quot;,
        ///        &quot;subjects&quot;: [
        ///          {
        ///            &quot;id&quot;: &quot;GGXVP1GBEE&quot;,
        ///            &quot;name&quot;: &quot;Vállalkozások pénzügyei, számvitel alapjai &quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OENIK_E {
            get {
                return ResourceManager.GetString("OENIK-E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;FromSyllabus&quot;: &quot;NBNEMI&quot;,
        ///    &quot;ToSyllabus&quot;: &quot;NBNEUM&quot;,
        ///    &quot;Subjects&quot;: {
        ///      &quot;GGXJA1SBNE&quot;: [ &quot;GGXJA1HBEE&quot; ],
        ///      &quot;GVXME1SBNE&quot;: [ &quot;GVXME1HBEE&quot; ],
        ///      &quot;KVXFI1PBNE&quot;: [ &quot;KVXFI1HBEE&quot; ],
        ///      &quot;NIXDR0PBNE&quot;: [ &quot;NIXDR0HBEE&quot;, &quot;NIEEL0HBEE&quot; ],
        ///      &quot;NIEIB0PBNE&quot;: [ &quot;NIEIB0HBEE&quot; ],
        ///      &quot;NIEOR1PBNE&quot;: [ &quot;NIEOR1HBEE&quot; ],
        ///      &quot;NIESA1PBNE&quot;: [ &quot;NIESA1HBEE&quot; ],
        ///      &quot;NIXAB0PBNE&quot;: [ &quot;NIXAB0HBEE&quot; ],
        ///      &quot;NIXBE1PBNE&quot;: [ &quot;NIXBE1IBEE&quot; ],
        ///      &quot;NIXBI1PBNE&quot;: [ &quot;NIXBI1HBEE&quot; ],
        ///      &quot;NIXBP1SBNE&quot;: [ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OENIK_E_equals {
            get {
                return ResourceManager.GetString("OENIK_E_equals", resourceCulture);
            }
        }
    }
}
